"""Add parent_id to Comment model

Revision ID: 074dbc7f49bf
Revises: b98bd74f9108
Create Date: 2024-09-21 13:17:25.224947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '074dbc7f49bf'
down_revision = 'b98bd74f9108'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comment_parent', 'comment', ['parent_id'], ['id'])  # Give a name here

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_parent', 'comment', type_='foreignkey')  # Name must match
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
